[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_blog = "CRFCZZVZoANEiovHnGxmiAVij1WhhtcCZgXJKSw2BAPe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "C:\\Users\\ashut\\.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
